import { randomInt, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { mkdir, readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { MlxBackend } from "./dist/backend.js";
import { config, hash, root as factoryRoot, validateRequest } from "./dist/config.js";
import { processIdentity } from "./dist/ownership.js";
import { qaRequest } from "./dist/qa.js";
import { atomicJson, createFactory } from "./dist/service.js";
import { ensureSetup } from "./dist/setup.js";
import { openReviewStore } from "./review-store.mjs";

export function workflowInput(input) {
  if (!input || Object.keys(input).some(key => !["request", "qa"].includes(key)) || !validateRequest(input.request))
    throw new Error(`Invalid workflow request: ${JSON.stringify(validateRequest.errors)}`);
  const request = { ...input.request, duration_seconds: input.request.duration_seconds ?? config.default_duration_seconds };
  const qa = input.qa ?? { clap: true, target: request.prompt.slice(0, 200), alternatives: ["Radio static noise", "A helicopter flying", "Silence"] };
  qaRequest("analyses", qa);
  return { request, qa };
}

// The CLI and studio both use this single setup/generation/QA/cut/bundle workflow.
export async function runWorkflow(job, { root, token, store, save, signal, backend = new MlxBackend(), setup = ensureSetup, computePort = config.port, fixture = false }) {
  let ready = false;
  const factory = await createFactory({ root, token, backend, fresh: true, ready: () => ready });
  const abort = () => { void backend.stop?.(); };
  signal.addEventListener("abort", abort);
  const stage = async status => { job.progress = status; await save(); signal.throwIfAborted(); };
  try {
    // Acquire the compute port before setup or any temporary-output cleanup.
    await new Promise((resolve, reject) => { factory.server.once("error", reject); factory.server.listen(computePort, "127.0.0.1", resolve); });
    const url = `http://127.0.0.1:${factory.server.address().port}`;
    const headers = { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };
    const call = async (path, value) => {
      const response = await fetch(`${url}${path}`, { method: value === undefined ? "GET" : "POST", headers: { ...headers, "Idempotency-Key": job.id },
        ...(value === undefined ? {} : { body: JSON.stringify(value) }), signal: AbortSignal.timeout(config.timeout_ms + 30000) });
      if (!response.ok) throw new Error(`${response.status}: ${await response.text()}`);
      return response;
    };
    await stage("setup");
    await setup(job.input.qa.clap === true, signal);
    signal.throwIfAborted();
    await backend.start?.();
    signal.throwIfAborted();
    const preserved = new Set(store.listCandidates().map(candidate => candidate.evidence.generation.id));
    // Recover completed sources left between generation and candidate publication, including legacy sessions.
    for (const runId of await readdir(join(root, "out/runs"))) {
      if (!/^[a-f0-9]{32}$/.test(runId)) continue;
      let generation;
      try { generation = JSON.parse(await readFile(join(root, "out/runs", runId, "run.json"), "utf8")); }
      catch (error) { if (error.code === "ENOENT") continue; throw error; }
      if (generation.status === "completed" && !preserved.has(runId)) store.saveCandidate({ attempt_id: runId, fixture, evaluation: null,
        evidence: { generation, analyses: [], cut_failure: null, reason: "Recovered source before temporary session cleanup" } },
        await readFile(join(root, "out/runs", runId, "audio.wav")));
    }
    await factory.beginSession();
    ready = true;
    await stage("generating");
    const response = await call("/v1/sound-effects", job.input.request);
    await response.arrayBuffer();
    const id = response.headers.get("x-run-id");
    const generation = await (await call(`/v1/runs/${id}`)).json();
    const source = await readFile(join(root, generation.audio_path));
    const preserve = async (evidence, audio = null) => {
      const candidate = store.saveCandidate({ attempt_id: job.id, fixture, evidence, evaluation: null }, source, audio);
      if (!job.candidate_ids.includes(candidate.candidate_sha256)) job.candidate_ids.push(candidate.candidate_sha256);
      await save();
      return candidate.candidate_sha256;
    };
    // Preserve generated bytes even if cancellation or QA prevents a delivered cut.
    await preserve({ generation, analyses: [], cut_failure: null, reason: "Source preserved before QA" });
    await stage("analyzing");
    const analysis = await (await call(`/v1/runs/${id}/analyses`, job.input.qa)).json();
    await preserve({ generation, analyses: [analysis], cut_failure: null, reason: "Source and QA preserved before cut" });
    await stage("cutting");
    const cutResponse = await call(`/v1/runs/${id}/cuts`, {});
    await cutResponse.arrayBuffer();
    const location = cutResponse.headers.get("location");
    if (!location?.startsWith(`/v1/runs/${id}/cuts/`)) throw new Error("Invalid cut metadata location");
    const cut = await (await call(location)).json();
    const evidence = JSON.parse(await readFile(cut.delivery.metadata, "utf8"));
    const candidate = await preserve(evidence, await readFile(cut.delivery.audio));
    return { id, audio: cut.delivery.audio, candidate_sha256: candidate,
      qa: { regions: analysis.result?.regions, rhythmic_warning: analysis.result?.rhythm?.suspected,
        clap: { status: analysis.result?.clap?.status, error: analysis.result?.clap?.error, ranking: analysis.result?.clap?.scores?.[0]?.ranking } },
      report: `${root}/out/runs/${id}/analyses/${analysis.id}/report.json` };
  } finally {
    signal.removeEventListener("abort", abort);
    await factory.close(); // Accepted QA drains within its existing subprocess deadlines.
    await backend.stop?.();
  }
}

export async function openJobs({ root = factoryRoot, token, execute = runWorkflow, ...execution } = {}) {
  if (typeof token !== "string" || !token) throw new Error("Private bearer token required");
  const directory = join(root, ".runtime/studio");
  const owners = join(directory, "owners");
  mkdirSync(owners, { recursive: true, mode: 0o700 });
  const owner = { pid: process.pid, identity: processIdentity(process.pid) };
  if (!owner.identity) throw new Error("Cannot establish workflow ownership");
  const lease = join(owners, `${randomUUID()}.json`);
  writeFileSync(lease, JSON.stringify(owner), { mode: 0o600, flag: "wx" });
  try {
    // Separate immutable claims avoid overwriting a newly acquired stale lock.
    for (const name of readdirSync(owners)) {
      const path = join(owners, name);
      if (path === lease) continue;
      let other;
      try { other = JSON.parse(readFileSync(path, "utf8")); } catch (error) { if (error.code === "ENOENT") continue; throw error; }
      if (processIdentity(other.pid) === other.identity) throw new Error("Studio/workflow already owned by a live process");
    }
  } catch (error) { unlinkSync(lease); throw error; }
  let active;
  let closing = false;
  const jobs = new Map();
  let store;
  try { store = openReviewStore(directory); } catch (error) { unlinkSync(lease); throw error; }
  const jobsPath = join(directory, "jobs");
  let writes = Promise.resolve();
  const save = job => {
    const snapshot = structuredClone(job);
    writes = writes.then(() => atomicJson(join(jobsPath, `${job.id}.json`), snapshot));
    return writes;
  };
  try {
    await mkdir(jobsPath, { recursive: true });
    for (const name of readdirSync(jobsPath).filter(name => /^[a-f0-9]{32}\.json$/.test(name))) {
      const job = JSON.parse(readFileSync(join(jobsPath, name), "utf8"));
      if (name !== `${job.id}.json`) throw new Error("Job identity mismatch");
      if (["running", "canceling"].includes(job.status)) {
        job.status = "interrupted";
        job.error = "Outcome uncertain; inspect preserved evidence and explicitly resume. No generation was replayed.";
        await save(job);
      }
      jobs.set(job.id, job);
    }
  } catch (error) { unlinkSync(lease); throw error; }
  const start = async job => {
    if (closing) throw Object.assign(new Error("Studio stopping"), { status: 503 });
    if (active) throw Object.assign(new Error("Factory busy; retry the same key"), { status: 429 });
    const controller = new AbortController();
    const operation = { job, controller };
    active = operation;
    job.status = "running";
    job.progress = "queued";
    const persisted = save(job);
    operation.promise = (async () => {
      try {
        await persisted;
        controller.signal.throwIfAborted();
        job.result = await execute(job, { root, token, store, save: () => save(job), signal: controller.signal, ...execution });
        job.status = controller.signal.aborted ? "canceled" : "completed";
      } catch (error) {
        job.status = controller.signal.aborted ? "canceled" : "failed";
        job.error = String(error);
      } finally {
        job.finished_at = new Date().toISOString();
        try { await save(job); } finally { active = undefined; }
      }
    })();
    operation.promise.catch(() => { closing = true; }); // Failed persistence poisons writes and prevents future cleanup.
    await persisted;
    return job;
  };
  let closed;
  return {
    store, list: () => [...jobs.values()], get: id => jobs.get(id),
    async submit(key, input, resuming) {
      if (typeof key !== "string" || !/^[a-zA-Z0-9_-]{1,128}$/.test(key)) throw Object.assign(new Error("Idempotency-Key required"), { status: 400 });
      input = workflowInput(input);
      const id = hash(key).slice(0, 32);
      const signature = hash(JSON.stringify({ request: { prompt: input.request.prompt, duration_seconds: input.request.duration_seconds, seed: input.request.seed }, qa: Object.fromEntries(Object.entries(input.qa).sort()) }));
      const existing = jobs.get(id);
      if (existing) {
        if (existing.signature !== signature) throw Object.assign(new Error("Idempotency key conflict"), { status: 409 });
        return existing;
      }
      if ([...jobs.values()].some(job => job.status === "interrupted" && !jobs.has(job.resumed_by) &&
          !(job === resuming && job.resumed_by === id)))
        throw Object.assign(new Error("Interrupted outcome requires explicit resume before new generation"), { status: 409 });
      const job = { id, signature, input: { ...input, request: { ...input.request, seed: input.request.seed ?? randomInt(2147483648) } },
        started_at: new Date().toISOString(), candidate_ids: [] };
      // Reserve synchronously before the first persistence await.
      const started = start(job);
      if (active?.job === job) jobs.set(id, job);
      return started;
    },
    async resume(id, key) {
      const job = jobs.get(id);
      if (!job || !["interrupted", "canceled", "failed"].includes(job.status)) throw Object.assign(new Error("Job is not resumable"), { status: 409 });
      if (typeof key !== "string" || !/^[a-zA-Z0-9_-]{1,128}$/.test(key)) throw Object.assign(new Error("New Idempotency-Key required"), { status: 400 });
      const replacement = hash(key).slice(0, 32);
      if (replacement === id) throw Object.assign(new Error("Resume requires a new idempotency key"), { status: 400 });
      if (job.resumed_by && job.resumed_by !== replacement) throw Object.assign(new Error("Job already resumed; retry its original resume key"), { status: 409 });
      if (jobs.has(replacement) && job.resumed_by !== replacement) throw Object.assign(new Error("Resume idempotency key conflict"), { status: 409 });
      job.resumed_by = replacement;
      await save(job);
      return this.submit(key, job.input, job); // Explicit new attempt; preserve the original uncertain outcome.
    },
    async cancel(id) {
      const job = jobs.get(id);
      if (!job) throw Object.assign(new Error("Unknown job"), { status: 404 });
      if (active?.job === job) {
        job.status = "canceling";
        const operation = active;
        await save(job);
        operation.controller.abort();
      }
      return job;
    },
    async wait() { await active?.promise; },
    close() {
      return closed ??= (async () => {
        closing = true;
        if (active) {
          const operation = active;
          operation.job.status = "canceling";
          try { await save(operation.job); } finally { operation.controller.abort(); }
          await operation.promise;
        }
        await writes;
        unlinkSync(lease);
      })();
    },
  };
}
